package beans;
// Generated 30-nov-2020 13:41:25 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Operaciones generated by hbm2java
 */
@Entity
@Table(name = "operaciones", catalog = "examencorchero")
public class Operaciones implements java.io.Serializable {

	private Integer codigo;
	private String dnivendedor;
	private String dnicomprador;
	private String concepto;
	private Integer precio;
	private Date fecha;
	private Integer tiempodevolucion;
	private Boolean canceable;

	public Operaciones() {
	}

	public Operaciones(String dnivendedor, String dnicomprador, String concepto, Integer precio, Date fecha,
			Integer tiempodevolucion, Boolean canceable) {
		this.dnivendedor = dnivendedor;
		this.dnicomprador = dnicomprador;
		this.concepto = concepto;
		this.precio = precio;
		this.fecha = fecha;
		this.tiempodevolucion = tiempodevolucion;
		this.canceable = canceable;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CODIGO", unique = true, nullable = false)
	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	@Column(name = "DNIVENDEDOR", length = 10)
	public String getDnivendedor() {
		return this.dnivendedor;
	}

	public void setDnivendedor(String dnivendedor) {
		this.dnivendedor = dnivendedor;
	}

	@Column(name = "DNICOMPRADOR", length = 10)
	public String getDnicomprador() {
		return this.dnicomprador;
	}

	public void setDnicomprador(String dnicomprador) {
		this.dnicomprador = dnicomprador;
	}

	@Column(name = "CONCEPTO", length = 20)
	public String getConcepto() {
		return this.concepto;
	}

	public void setConcepto(String concepto) {
		this.concepto = concepto;
	}

	@Column(name = "PRECIO")
	public Integer getPrecio() {
		return this.precio;
	}

	public void setPrecio(Integer precio) {
		this.precio = precio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA", length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "TIEMPODEVOLUCION")
	public Integer getTiempodevolucion() {
		return this.tiempodevolucion;
	}

	public void setTiempodevolucion(Integer tiempodevolucion) {
		this.tiempodevolucion = tiempodevolucion;
	}

	@Column(name = "CANCEABLE")
	public Boolean getCanceable() {
		return this.canceable;
	}

	public void setCanceable(Boolean canceable) {
		this.canceable = canceable;
	}

}
