package beans;
// Generated 30-nov-2020 13:41:25 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tiempodevoluciones generated by hbm2java
 */
@Entity
@Table(name = "tiempodevoluciones", catalog = "examencorchero")
public class Tiempodevoluciones implements java.io.Serializable {

	private int tiempo;

	public Tiempodevoluciones() {
	}

	public Tiempodevoluciones(int tiempo) {
		this.tiempo = tiempo;
	}

	@Id

	@Column(name = "tiempo", nullable = false)
	public int getTiempo() {
		return this.tiempo;
	}

	public void setTiempo(int tiempo) {
		this.tiempo = tiempo;
	}

}
